
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"

sudo: true

before_install:
  - sudo pip install coverage --user
  - sudo pip install nose

install:
  - sudo python setup.py install

script: nosetests

after_sucess:
 - coverage run tests
 - bash <(curl -s https://codecov.io/bash)

